version: "3"
services:
  web:
    image: nginx
    container_name: ${PROJECT_NAME}-web
    depends_on:
      - app
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ${PROJECT_PATH}:/work
      - ./docker/nginx/logs:/var/log/nginx/
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ./docker/php
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    ports:
      - ${LARAVEL_SERVER_PORT}:8000
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  db:
    container_name: ${PROJECT_NAME}-db
    build:
      context: ./docker/mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql/logs:/var/log/mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_TESTING_DATABASE=${MYSQL_TESTING_DATABASE}
    ports:
      - ${MYSQL_PORT}:3306

  node:
    container_name: ${PROJECT_NAME}-node
    image: node:11-alpine
    volumes:
      - ${PROJECT_PATH}:/work
    working_dir: /work

  redis:
    container_name: ${PROJECT_NAME}_redis
    image: redis:alpine

volumes:
  db-data:
    driver: local
